# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./MyGraphicsCircleItem.h \
    ./MyGraphicsEllipseItem.h \
    ./MyGraphicsRecItem.h \
    ./MygraphicsLinePre.h \
    ./mainWindow.h \
    ./MyGraphicsScene.h \
    ./MyGraphicsView.h \
    ./RulerWidget.h \
    ./MyMianArea.h
SOURCES += ./MyGraphicsCircleItem.cpp \
    ./MyGraphicsEllipseItem.cpp \
    ./MyGraphicsRecItem.cpp \
    ./MyGraphicsScene.cpp \
    ./MyGraphicsView.cpp \
    ./MygraphicsLinePre.cpp \
    ./RulerWidget.cpp \
    ./mainWindow.cpp \
    ./main.cpp \
    ./MyMianArea.cpp
FORMS += ./mainWindow.ui
RESOURCES += mainWindow.qrc
