# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core gui widgets
TEMPLATE = app
TARGET = QtLightPrint
DESTDIR = ../Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./CUDrvE.h \
    ./MyGraphicsCircleItem.h \
    ./MyGraphicsEllipseItem.h \
    ./MyGraphicsRecItem.h \
    ./MyKedu.h \
    ./MyMianArea.h \
    ./MygraphicsLinePre.h \
    ./MyleftKedu.h \
    ./MyGraphicsScene.h \
    ./MyGraphicsView.h \
    ./mainWindow.h
SOURCES += ./MyGraphicsCircleItem.cpp \
    ./MyGraphicsEllipseItem.cpp \
    ./MyGraphicsRecItem.cpp \
    ./MyGraphicsScene.cpp \
    ./MyGraphicsView.cpp \
    ./MyKedu.cpp \
    ./MyMianArea.cpp \
    ./MygraphicsLinePre.cpp \
    ./MyleftKedu.cpp \
    ./main.cpp \
    ./mainWindow.cpp
FORMS += ./mainWindow.ui
RESOURCES += mainWindow.qrc
LIBS += -LD:\QtCode\QtLightPrint\QtLightPrint\libs -lCUDrvE
