# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += core gui widgets \
    quick
QT += xml
TEMPLATE = app
TARGET = QtLightPrint
DESTDIR = ../QtLightPrint/debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./ItemAdjust.h \
    ./PrintParams.h \
    ./mainWindow.h \
    FileHandel/itemfileclass.h \
    FileHandel/pltfilehandle.h \
    FileHandel/qlptfilehandle.h \
    GraphicsItems/MyGraphicsCircleItem.h \
    GraphicsItems/MyGraphicsEllipseItem.h \
    GraphicsItems/MyGraphicsRecItem.h \
    GraphicsItems/MyGraphicsScene.h \
    GraphicsItems/MyGraphicsView.h \
    GraphicsItems/MyKedu.h \
    GraphicsItems/MyMianArea.h \
    GraphicsItems/MygraphicsLinePre.h \
    GraphicsItems/MyleftKedu.h \
    GraphicsItems/mygraphicscodeitem.h \
    GraphicsItems/mygraphicscurvelineitem.h \
    GraphicsItems/mygraphicsgroupitem.h \
    GraphicsItems/mygraphicslineitem.h \
    GraphicsItems/mygraphicspixmapitem.h \
    GraphicsItems/mygraphicspolygonitem.h \
    GraphicsItems/mygraphicstextitem.h \
    GraphicsItems/mylabel.h \
    ItemHandle/itemalignhandle.h \
    ItemHandle/itemchangehandle.h \
    ItemHandle/itemprinthandle.h \
    ItemHandle/itemscalehandle.h \
    ItemHandle/itemselecthandle.h \
    ItemHandle/itemsizehandle.h \
    Widgets/advancedwidget.h \
    Widgets/bottomdockwidget.h \
    Widgets/configtabwidget.h \
    Widgets/configtabwidgetarea.h \
    Widgets/configtabwidgetlasercontrol.h \
    Widgets/configtabwidgetother.h \
    Widgets/configtabwidgetport.h \
    Widgets/configtabwidgetred.h \
    Widgets/configwidget.h \
    Widgets/dialogcalculaterecommendvalues.h \
    Widgets/dialogcalculationratio.h \
    Widgets/dialogpasswordsetting.h \
    Widgets/widgetco2.h \
    Widgets/widgetfiber.h \
    Widgets/widgetuv.h \
    Widgets/widgetyag.h \
    libsHeaders/CUDrvE.h \
    libsHeaders/CUDrvE_global.h \
    libsHeaders/ZXingWriter.h \
    ./thirdcurve.h


SOURCES += ./ItemAdjust.cpp \
    FileHandel/itemfileclass.cpp \
    FileHandel/pltfilehandle.cpp \
    FileHandel/qlptfilehandle.cpp \
    GraphicsItems/MyGraphicsCircleItem.cpp \
    GraphicsItems/MyGraphicsEllipseItem.cpp \
    GraphicsItems/MyGraphicsRecItem.cpp \
    GraphicsItems/MyGraphicsScene.cpp \
    GraphicsItems/MyGraphicsView.cpp \
    GraphicsItems/MyKedu.cpp \
    GraphicsItems/MyMianArea.cpp \
    GraphicsItems/MygraphicsLinePre.cpp \
    GraphicsItems/MyleftKedu.cpp \
    GraphicsItems/mygraphicscodeitem.cpp \
    GraphicsItems/mygraphicscurvelineitem.cpp \
    GraphicsItems/mygraphicsgroupitem.cpp \
    GraphicsItems/mygraphicslineitem.cpp \
    GraphicsItems/mygraphicspixmapitem.cpp \
    GraphicsItems/mygraphicspolygonitem.cpp \
    GraphicsItems/mygraphicstextitem.cpp \
    GraphicsItems/mylabel.cpp \
    ItemHandle/itemalignhandle.cpp \
    ItemHandle/itemchangehandle.cpp \
    ItemHandle/itemprinthandle.cpp \
    ItemHandle/itemscalehandle.cpp \
    ItemHandle/itemselecthandle.cpp \
    ItemHandle/itemsizehandle.cpp \
    Widgets/advancedwidget.cpp \
    Widgets/bottomdockwidget.cpp \
    Widgets/configtabwidget.cpp \
    Widgets/configtabwidgetarea.cpp \
    Widgets/configtabwidgetlasercontrol.cpp \
    Widgets/configtabwidgetother.cpp \
    Widgets/configtabwidgetport.cpp \
    Widgets/configtabwidgetred.cpp \
    Widgets/configwidget.cpp \
    Widgets/dialogcalculaterecommendvalues.cpp \
    Widgets/dialogcalculationratio.cpp \
    Widgets/dialogpasswordsetting.cpp \
    Widgets/widgetco2.cpp \
    Widgets/widgetfiber.cpp \
    Widgets/widgetuv.cpp \
    Widgets/widgetyag.cpp \
    ./PrintParams.cpp \
    ./main.cpp \
    ./mainWindow.cpp \
    ./thirdcurve.cpp


FORMS += ./mainWindow.ui
RESOURCES += mainWindow.qrc

DISTFILES += \
    .editorconfig \
    .gitattributes \
    .qmake.stash \
    QtLightPrint.pri \
    QtLightPrint.pro.user \
    cpp.hint \
    lang_English.qm \
    lang_zh_CN.qm
TRANSLATIONS += lang_English.ts\
                lang_zh_CN.ts\


LIBS += -L$$PWD/libs/ -lCUDrvE libZXingWriter
